### ISSUE TITLE
Will there be support for file uploads?

### ISSUE THREAD

**Issue by phochste** [danielbeeke/rdf-form#12]
I've added today a challenge https://github.com/SolidLabResearch/Challenges/issues/19 for SolidLabResearch and @rubensworks mentioned pointed me to your project. It is great to see your solution! Is there a way for doing file loads via this mechanism?

**Comment by danielbeeke** [comment]
Hi @phochste 

I have recently added [Uppy](https://uppy.io/) S3 multipart support.
It is not bug free yet.

We are using rdf-form for a headless cms on top of Apache Jena.
In our use case we are using BackBlaze with their S3 compatible API.
This product: rdf-form is not yet bug free, but slowly we are getting there.
At the moment it is also import to note that we a refactor should be done on how translations are added.
At the moment it is possible  to lose types:

"22-01-2020"@en

I am thinking of how to solve that.
Personally I would have loved if RDF would allow that with types.

**Comment by phochste** [comment]
Thanks for this!

**Comment by phochste** [comment]
About the date types is not that something that doesn't need to be part of the data model but more of a separate display component, or even two seperate triples a string and an inferred date? 

There is difference between a string as entered by a human and the inferred ISO date. In library context that is also the case where there is, for instance, a distinction between the French Republican calendar date as seen on a book ("11 Frimaire, Year XIII") and the ISO date ("1804-12-02").

The predicate you would use for the date would inform linked data aplications how to interpret the date. E.g.

```
<https://example.org/record/123> <http://example.org/world/clock#FrenchRepublican> "11 Frimaire, Year XIII"
```
