### ISSUE TITLE
Support for SHACL

### ISSUE THREAD

**Issue by mielvds** [danielbeeke/rdf-form#14]
Hi! I had a talk with @phochste earlier, so I'm registering this before I forget. I would be interested in contributing to a SHACL/dash bridge for rdf-form. To not change any code, this could be implemented using SPARQL construct.

**Comment by danielbeeke** [comment]
Hi Miel, thanks for the issue and your interest in contributing a SPARQL construct!

In a second iteration of rdf-form I am working on SHACL support:

https://github.com/danielbeeke/frm/

It is a work in progress but will have nicer support for a lot of things.

**Comment by danielbeeke** [comment]
I will close this for now. Ongoing work is in frm.
